/// Pure-Dart defaults shared by reader scope resolution and offline audits.
const defaultAiStructureAppendixUnits = <String>[
  '附录',
  '参考书目',
  '参考文献',
  '参考资料',
  '人名索引',
  '地名索引',
  '主题索引',
  '关键词索引',
  '索引',
  '致谢',
  '谢辞',
  '鸣谢',
  '后记',
  '跋',
  '注释',
  '年表',
  '词汇表',
  '术语表',
  '缩略语表',
  '勘误',
  '勘误表',
  '卷末',
  '书末',
  '前言',
  '序言',
  '序',
  '自序',
  '代序',
  '弁言',
  '小引',
  '凡例',
  '出版说明',
  '出版前言',
  '出版后记',
  '出版者的话',
  '编者按',
  '导读',
  '题记',
  '题词',
  '题辞',
  '题献',
  '献词',
  '献页',
  '致献',
  '重印前记',
  '重印后记',
  '再版前记',
  '再版后记',
  '再版说明',
  '重印说明',
  '修订说明',
  '修订版说明',
  '校订说明',
  '点校说明',
  '整理说明',
  '编译说明',
  '编写说明',
  '译者序',
  '译者前言',
  '译者后记',
  '译后记',
  '译序',
  '校后记',
  '编后',
  '编后记',
  '文前辅文',
  '文前',
  '辅文',
  '前置部分',
  '卷首',
  '卷首语',
  '扉页',
  '书名页',
  '版权页',
  '衬页',
  '环衬',
  '飞页',
  '插页',
  '内容简介',
  '内容提要',
  '图书简介',
  '作者简介',
  '关于作者',
  '关于本书',
  '作者小传',
  '作者生平',
  '制作说明',
  '画廊',
  '系列封面',
  '封面画廊',
  '封面语',
  '封底语',
  '!序曲',
  '!序章',
  '!序幕',
  '!序篇',
];

const defaultAiStructureMetadataUnits = <String>[
  '目录',
  '总目录',
  '全书目录',
  '章节目录',
  '目次',
  '版权',
  '版权信息',
  '版权页',
  '版权记录',
  '出版',
  '出版信息',
  '出版说明',
  '出版记录',
  '出版前言',
  '出版后记',
  '图书在版编目',
  '版本记录',
  '封面',
  '总封面',
  '封底',
  '扉页',
  '书名页',
  '护封',
  '腰封',
];

bool matchesAiStructureSupplementTitle(
  String raw, {
  List<String> appendixUnits = defaultAiStructureAppendixUnits,
  List<String> metadataUnits = defaultAiStructureMetadataUnits,
}) {
  final title = raw.trim().replaceAll(RegExp(r'\s+'), '');
  if (title.isEmpty) return true;
  if (RegExp(r'^作者.{0,16}(?:小传|生平|简介)$').hasMatch(title)) {
    return true;
  }
  if (metadataUnits.any((word) => word.trim() == title)) return true;
  final exclusions = appendixUnits
      .where((word) => word.trim().startsWith('!'))
      .map((word) => word.trim().substring(1).trim())
      .where((word) => word.isNotEmpty);
  if (exclusions.any(title.startsWith)) return false;
  return appendixUnits
      .where((word) => !word.trim().startsWith('!'))
      .map((word) => word.trim())
      .where((word) => word.isNotEmpty)
      .any(title.startsWith);
}
